# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование здания')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('business_hours', models.TextField(max_length=500, verbose_name='Часы работы')),
                ('visiting_hours', models.TextField(blank=True, max_length=500, verbose_name='Часы приема')),
            ],
            options={
                'verbose_name_plural': 'Филиалы',
                'verbose_name': 'Филиал',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=200, verbose_name='Сокращенное наименование')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('website', models.URLField(verbose_name='Сайт')),
            ],
            options={
                'verbose_name_plural': 'Информация об организации',
                'verbose_name': 'Информация об организации',
            },
        ),
    ]
